WARP program for graph SeeSpray
Scheduler Name: Priority
numFaults: 1
M: 0.9
E2E: 0.99
nChannels: 16
Time Slot	B1	B2	B3	B4	B5	B6	B7	B8	C1	C10	C11	C12	C13	C14	C15	C16	C17	C18	C19	C2	C20	C21	C22	C23	C24	C25	C26	C27	C28	C29	C3	C30	C4	C5	C6	C7	C8	C9
0	wait(#1)	wait(#1)	wait(#1)	wait(#1)	wait(#1)	wait(#1)	wait(#1)	wait(#1)	if has(F1A) push(F1A: C1 -> B1, #1)	sleep	sleep	sleep	if has(F13A) push(F13A: C13 -> B4, #1)	sleep	sleep	if has(F16A) push(F16A: C16 -> B5, #1)	sleep	sleep	sleep	sleep	if has(F20A) push(F20A: C20 -> B6, #1)	sleep	sleep	sleep	if has(F24A) push(F24A: C24 -> B7, #1)	sleep	sleep	sleep	if has(F28A) push(F28A: C28 -> B8, #1)	sleep	sleep	sleep	sleep	if has(F5A) push(F5A: C5 -> B2, #1)	sleep	sleep	sleep	if has(F9A) push(F9A: C9 -> B3, #1)
1	wait(#2)	wait(#2)	wait(#2)	wait(#2)	wait(#2)	wait(#2)	wait(#2)	wait(#2)	if has(F1A) push(F1A: C1 -> B1, #2)	sleep	sleep	sleep	if has(F13A) push(F13A: C13 -> B4, #2)	sleep	sleep	if has(F16A) push(F16A: C16 -> B5, #2)	sleep	sleep	sleep	sleep	if has(F20A) push(F20A: C20 -> B6, #2)	sleep	sleep	sleep	if has(F24A) push(F24A: C24 -> B7, #2)	sleep	sleep	sleep	if has(F28A) push(F28A: C28 -> B8, #2)	sleep	sleep	sleep	sleep	if has(F5A) push(F5A: C5 -> B2, #2)	sleep	sleep	sleep	if has(F9A) push(F9A: C9 -> B3, #2)
2	wait(#1)	wait(#1)	wait(#1)	wait(#1)	wait(#1)	wait(#1)	wait(#1)	wait(#1)	sleep	if has(F10A) push(F10A: C10 -> B3, #1)	sleep	sleep	sleep	if has(F14A) push(F14A: C14 -> B4, #1)	sleep	sleep	if has(F17A) push(F17A: C17 -> B5, #1)	sleep	sleep	if has(F2A) push(F2A: C2 -> B1, #1)	sleep	if has(F21A) push(F21A: C21 -> B6, #1)	sleep	sleep	sleep	if has(F25A) push(F25A: C25 -> B7, #1)	sleep	sleep	sleep	if has(F29A) push(F29A: C29 -> B8, #1)	sleep	sleep	sleep	sleep	if has(F6A) push(F6A: C6 -> B2, #1)	sleep	sleep	sleep
3	wait(#2)	wait(#2)	wait(#2)	wait(#2)	wait(#2)	wait(#2)	wait(#2)	wait(#2)	sleep	if has(F10A) push(F10A: C10 -> B3, #2)	sleep	sleep	sleep	if has(F14A) push(F14A: C14 -> B4, #2)	sleep	sleep	if has(F17A) push(F17A: C17 -> B5, #2)	sleep	sleep	if has(F2A) push(F2A: C2 -> B1, #2)	sleep	if has(F21A) push(F21A: C21 -> B6, #2)	sleep	sleep	sleep	if has(F25A) push(F25A: C25 -> B7, #2)	sleep	sleep	sleep	if has(F29A) push(F29A: C29 -> B8, #2)	sleep	sleep	sleep	sleep	if has(F6A) push(F6A: C6 -> B2, #2)	sleep	sleep	sleep
4	wait(#1)	wait(#1)	wait(#1)	wait(#1)	wait(#1)	wait(#1)	wait(#1)	wait(#1)	sleep	sleep	if has(F11A) push(F11A: C11 -> B3, #1)	sleep	sleep	sleep	if has(F15A) push(F15A: C15 -> B4, #1)	sleep	sleep	if has(F18A) push(F18A: C18 -> B5, #1)	sleep	sleep	sleep	sleep	if has(F22A) push(F22A: C22 -> B6, #1)	sleep	sleep	sleep	if has(F26A) push(F26A: C26 -> B7, #1)	sleep	sleep	sleep	if has(F3A) push(F3A: C3 -> B1, #1)	if has(F30A) push(F30A: C30 -> B8, #1)	sleep	sleep	sleep	if has(F7A) push(F7A: C7 -> B2, #1)	sleep	sleep
5	wait(#2)	wait(#2)	wait(#2)	wait(#2)	wait(#2)	wait(#2)	wait(#2)	wait(#2)	sleep	sleep	if has(F11A) push(F11A: C11 -> B3, #2)	sleep	sleep	sleep	if has(F15A) push(F15A: C15 -> B4, #2)	sleep	sleep	if has(F18A) push(F18A: C18 -> B5, #2)	sleep	sleep	sleep	sleep	if has(F22A) push(F22A: C22 -> B6, #2)	sleep	sleep	sleep	if has(F26A) push(F26A: C26 -> B7, #2)	sleep	sleep	sleep	if has(F3A) push(F3A: C3 -> B1, #2)	if has(F30A) push(F30A: C30 -> B8, #2)	sleep	sleep	sleep	if has(F7A) push(F7A: C7 -> B2, #2)	sleep	sleep
6	wait(#1)	wait(#1)	wait(#1)	sleep	wait(#1)	wait(#1)	wait(#1)	sleep	sleep	sleep	sleep	if has(F12A) push(F12A: C12 -> B3, #1)	sleep	sleep	sleep	sleep	sleep	sleep	if has(F19A) push(F19A: C19 -> B5, #1)	sleep	sleep	sleep	sleep	if has(F23A) push(F23A: C23 -> B6, #1)	sleep	sleep	sleep	if has(F27A) push(F27A: C27 -> B7, #1)	sleep	sleep	sleep	sleep	if has(F4A) push(F4A: C4 -> B1, #1)	sleep	sleep	sleep	if has(F8A) push(F8A: C8 -> B2, #1)	sleep
7	wait(#2)	wait(#2)	wait(#2)	sleep	wait(#2)	wait(#2)	wait(#2)	sleep	sleep	sleep	sleep	if has(F12A) push(F12A: C12 -> B3, #2)	sleep	sleep	sleep	sleep	sleep	sleep	if has(F19A) push(F19A: C19 -> B5, #2)	sleep	sleep	sleep	sleep	if has(F23A) push(F23A: C23 -> B6, #2)	sleep	sleep	sleep	if has(F27A) push(F27A: C27 -> B7, #2)	sleep	sleep	sleep	sleep	if has(F4A) push(F4A: C4 -> B1, #2)	sleep	sleep	sleep	if has(F8A) push(F8A: C8 -> B2, #2)	sleep
8	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
9	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
10	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
11	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
12	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
13	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
14	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
15	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
16	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
17	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
18	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
19	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
20	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
21	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
22	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
23	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
24	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
25	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
26	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
27	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
28	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
29	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
30	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
31	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
32	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
33	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
34	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
35	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
36	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
37	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
38	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
39	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
40	if has(F1B) push(F1B: B1 -> C1, #1)	if has(F5B) push(F5B: B2 -> C5, #1)	if has(F9B) push(F9B: B3 -> C9, #1)	if has(F13B) push(F13B: B4 -> C13, #1)	if has(F16B) push(F16B: B5 -> C16, #1)	if has(F20B) push(F20B: B6 -> C20, #1)	if has(F24B) push(F24B: B7 -> C24, #1)	if has(F28B) push(F28B: B8 -> C28, #1)	wait(#1)	sleep	sleep	sleep	wait(#1)	sleep	sleep	wait(#1)	sleep	sleep	sleep	sleep	wait(#1)	sleep	sleep	sleep	wait(#1)	sleep	sleep	sleep	wait(#1)	sleep	sleep	sleep	sleep	wait(#1)	sleep	sleep	sleep	wait(#1)
41	if has(F1B) push(F1B: B1 -> C1, #2)	if has(F5B) push(F5B: B2 -> C5, #2)	if has(F9B) push(F9B: B3 -> C9, #2)	if has(F13B) push(F13B: B4 -> C13, #2)	if has(F16B) push(F16B: B5 -> C16, #2)	if has(F20B) push(F20B: B6 -> C20, #2)	if has(F24B) push(F24B: B7 -> C24, #2)	if has(F28B) push(F28B: B8 -> C28, #2)	wait(#2)	sleep	sleep	sleep	wait(#2)	sleep	sleep	wait(#2)	sleep	sleep	sleep	sleep	wait(#2)	sleep	sleep	sleep	wait(#2)	sleep	sleep	sleep	wait(#2)	sleep	sleep	sleep	sleep	wait(#2)	sleep	sleep	sleep	wait(#2)
42	if has(F2B) push(F2B: B1 -> C2, #3)	if has(F6B) push(F6B: B2 -> C6, #3)	if has(F10B) push(F10B: B3 -> C10, #3)	if has(F14B) push(F14B: B4 -> C14, #3)	if has(F17B) push(F17B: B5 -> C17, #3)	if has(F21B) push(F21B: B6 -> C21, #3)	if has(F25B) push(F25B: B7 -> C25, #3)	if has(F29B) push(F29B: B8 -> C29, #3)	sleep	wait(#3)	sleep	sleep	sleep	wait(#3)	sleep	sleep	wait(#3)	sleep	sleep	wait(#3)	sleep	wait(#3)	sleep	sleep	sleep	wait(#3)	sleep	sleep	sleep	wait(#3)	sleep	sleep	sleep	sleep	wait(#3)	sleep	sleep	sleep
43	if has(F2B) push(F2B: B1 -> C2, #4)	if has(F6B) push(F6B: B2 -> C6, #4)	if has(F10B) push(F10B: B3 -> C10, #4)	if has(F14B) push(F14B: B4 -> C14, #4)	if has(F17B) push(F17B: B5 -> C17, #4)	if has(F21B) push(F21B: B6 -> C21, #4)	if has(F25B) push(F25B: B7 -> C25, #4)	if has(F29B) push(F29B: B8 -> C29, #4)	sleep	wait(#4)	sleep	sleep	sleep	wait(#4)	sleep	sleep	wait(#4)	sleep	sleep	wait(#4)	sleep	wait(#4)	sleep	sleep	sleep	wait(#4)	sleep	sleep	sleep	wait(#4)	sleep	sleep	sleep	sleep	wait(#4)	sleep	sleep	sleep
44	if has(F3B) push(F3B: B1 -> C3, #5)	if has(F7B) push(F7B: B2 -> C7, #5)	if has(F11B) push(F11B: B3 -> C11, #5)	if has(F15B) push(F15B: B4 -> C15, #5)	if has(F18B) push(F18B: B5 -> C18, #5)	if has(F22B) push(F22B: B6 -> C22, #5)	if has(F26B) push(F26B: B7 -> C26, #5)	if has(F30B) push(F30B: B8 -> C30, #5)	sleep	sleep	wait(#5)	sleep	sleep	sleep	wait(#5)	sleep	sleep	wait(#5)	sleep	sleep	sleep	sleep	wait(#5)	sleep	sleep	sleep	wait(#5)	sleep	sleep	sleep	wait(#5)	wait(#5)	sleep	sleep	sleep	wait(#5)	sleep	sleep
45	if has(F3B) push(F3B: B1 -> C3, #6)	if has(F7B) push(F7B: B2 -> C7, #6)	if has(F11B) push(F11B: B3 -> C11, #6)	if has(F15B) push(F15B: B4 -> C15, #6)	if has(F18B) push(F18B: B5 -> C18, #6)	if has(F22B) push(F22B: B6 -> C22, #6)	if has(F26B) push(F26B: B7 -> C26, #6)	if has(F30B) push(F30B: B8 -> C30, #6)	sleep	sleep	wait(#6)	sleep	sleep	sleep	wait(#6)	sleep	sleep	wait(#6)	sleep	sleep	sleep	sleep	wait(#6)	sleep	sleep	sleep	wait(#6)	sleep	sleep	sleep	wait(#6)	wait(#6)	sleep	sleep	sleep	wait(#6)	sleep	sleep
46	if has(F4B) push(F4B: B1 -> C4, #7)	if has(F8B) push(F8B: B2 -> C8, #7)	if has(F12B) push(F12B: B3 -> C12, #7)	sleep	if has(F19B) push(F19B: B5 -> C19, #7)	if has(F23B) push(F23B: B6 -> C23, #7)	if has(F27B) push(F27B: B7 -> C27, #7)	sleep	sleep	sleep	sleep	wait(#7)	sleep	sleep	sleep	sleep	sleep	sleep	wait(#7)	sleep	sleep	sleep	sleep	wait(#7)	sleep	sleep	sleep	wait(#7)	sleep	sleep	sleep	sleep	wait(#7)	sleep	sleep	sleep	wait(#7)	sleep
47	if has(F4B) push(F4B: B1 -> C4, #8)	if has(F8B) push(F8B: B2 -> C8, #8)	if has(F12B) push(F12B: B3 -> C12, #8)	sleep	if has(F19B) push(F19B: B5 -> C19, #8)	if has(F23B) push(F23B: B6 -> C23, #8)	if has(F27B) push(F27B: B7 -> C27, #8)	sleep	sleep	sleep	sleep	wait(#8)	sleep	sleep	sleep	sleep	sleep	sleep	wait(#8)	sleep	sleep	sleep	sleep	wait(#8)	sleep	sleep	sleep	wait(#8)	sleep	sleep	sleep	sleep	wait(#8)	sleep	sleep	sleep	wait(#8)	sleep
48	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
49	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep	sleep
// All flows meet their deadlines
